version: "3.5"

services:
  main-reverseproxy:
      image: main-reverseproxy:latest
      container_name: Main-Reverse-Proxy
      ports:
        - 8080:8080
        - 80:80
        - 443:443
      volumes:
        - Reverse_Proxy_Data:/data
      build: 
        context: .
        dockerfile: Dockerfile-mainproxy
      command: "/init.sh"
      networks:
      - proxy-net

volumes:
  Reverse_Proxy_Data:
    external: true
  
networks:
  proxy-net:
    external: true
